#!/bin/sh
yay -S libdisplay-info-git hyprland-nvidia-git micro nerd-fonts-complete-starship wofi dunst jq eww-wayland swayidle swaylock-effects-git swaylockd sway-audio-idle-inhibit-git bc pamixer light-git papirus-icon-theme playerctl cava kitty xdg-desktop-portal-wlr grim slurp wl-clipboard socat swappy cliphist hyprpicker-git nm-connection-editor dictd wl-clip-persist-git blueberry sddm 



echo "software installed"
sleep 5
echo "5"
echo "4"
echo "3" 
echo "2"
echo "1"
git clone https://github.com/AmadeusWM/dotfiles-hyprland
cd dotfiles-hyprland/
mkdir ~/.config/hypr
cp -r ./* ~/.config/hypr
echo "theme done"
sleep 5
echo "5"
echo "4"
echo "3" 
echo "2"
echo "1"
cd ..
git clone https://github.com/Rudra2002/hyprland-script
cd hyprland-script/
cp -r __hyprland.conf ~/.config/hypr/__hyprland.conf 
mv ~/.config/hypr/__hyprland.conf ~/.config/hypr/hyprland.conf
rm ~/.config/hypr/_hyprland.conf

echo "my theme done"
sleep 5
echo "5"
echo "4"
echo "3" 
echo "2"
echo "1"

sudo cp wrappedhl /usr/local/bin/wrappedhl
sudo chmod +x wrappedhl
sudo chmod +u wrappedhl
echo " done wrappedhl"
sleep 5
echo "5"
echo "4"
echo "3" 
echo "2"
echo "1"
sudo systemctl enable sddm.service
sudo mkdir /usr/share/wayland-sessions/
sudo cp _hyprland.desktop /usr/share/wayland-sessions/hyprland.desktop
echo "sddm done"
